import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 번역 데이터
const translations = {
  ko: {
    'app.title': 'Awesome Nano Banana Pro',
    'hero.subtitle': '엄선된 컬렉션',
    'hero.title': 'Awesome Nano Banana Pro',
    'hero.description': '최고의 Nano Banana 프롬프트, 이미지 생성 스타일, 고급 AI 시각 실험을 위한 컬렉션입니다.',
    'hero.tryButton': 'Nano Banana Pro 사용해보기',
    'gallery.title': '프롬프트 탐색',
    'gallery.description': 'Nano Banana Pro를 위한 {count}개의 신중하게 큐레이션된 프롬프트 발견',
    'gallery.noResults': '이 카테고리에서 프롬프트를 찾을 수 없습니다.',
    'nav.print': '인쇄',
    'card.view': '보기',
    'card.copy': '복사',
    'card.copied': '복사됨!',
    'card.source': '출처',
    'modal.prompt': '프롬프트',
    'modal.copyPrompt': '프롬프트 복사',
    'footer.madeWith': 'AI 커뮤니티를 위해 ❤️로 제작되었습니다',
    'footer.lastUpdated': '최종 업데이트',
    'footer.viewOnGitHub': 'GitHub에서 보기',
    'category.all': '전체',
    'category.1': '사진 리얼리즘 & 미학',
    'category.2': '창의적 실험',
    'category.3': '교육 & 지식',
    'category.4': '이커머스 & 가상 스튜디오',
    'category.5': '직장 & 생산성',
    'category.6': '사진 편집 & 복원',
    'category.7': '인테리어 디자인',
    'category.8': '소셜 미디어 & 마케팅',
    'category.9': '일상 생활 & 번역',
    'category.10': '소셜 네트워킹 & 아바타',
    // 프롬프트 번역
    'prompt.1_1.title': '하이퍼 리얼리스틱 군중 구성',
    'prompt.1_1.description': '여러 유명 인물과 특정 조명을 가진 복잡한 구도 처리.',
    'prompt.1_2.title': '2000년대 거울 셀피',
    'prompt.1_2.description': '플래시 사진과 향수를 불러일으키는 요소로 진정한 2000년대 초 미학을 생성하는 구조화된 JSON 프롬프트.',
    'prompt.1_3.title': '빅토리아 시크릿 스타일 사진 촬영',
    'prompt.1_3.description': '복잡한 세부사항을 가진 고급스러운 백스테이지 스타일 패션 사진 제작에 적합.',
    'prompt.1_4.title': '1990년대 카메라 스타일 초상화',
    'prompt.1_4.description': '특정 필름 질감, 플래시 사진, 시대별 분위기를 재현하는 모델의 능력 테스트.',
    'prompt.1_5.title': '원클릭 비즈니스 사진 (실리콘 밸리 스타일)',
    'prompt.1_5.description': '특정 렌즈와 조명 지침을 사용하여 캐주얼 사진을 전문 스튜디오 헤드샷으로 변환.',
    'prompt.1_6.title': '감성적인 필름 사진',
    'prompt.1_6.description': '얼굴 일관성을 유지하면서 시네마틱하고 향수를 불러일으키는 "Kodak Portra" 룩 생성.',
    'prompt.1_7.title': '전문 프로필 사진 생성기',
    'prompt.1_7.description': '셀피에서 전문 프로필 사진 생성',
    'prompt.1_8.title': '스포트라이트 하이퍼리얼리스틱 애니메 초상화',
    'prompt.1_8.description': '극적인 조명을 가진 하이퍼리얼리스틱 애니메 스타일 초상화',
    'prompt.1_9.title': '욕실 거울 셀피',
    'prompt.1_9.description': '특정 스타일링과 구도로 솔직한 거울 셀피 생성',
    'prompt.1_10.title': '칠판 애니메 아트 문서화',
    'prompt.1_10.description': '칠판 애니메 그림의 사진 리얼리스틱 문서화',
    'prompt.1_11.title': '눈 속 강아지와 함께한 초상화',
    'prompt.1_11.description': '강아지와 함께한 겨울 초상화 생성',
    'prompt.1_12.title': '어안 영화 캐릭터 셀피',
    'prompt.1_12.description': '영화 캐릭터와 함께한 360도 셀피',
    'prompt.1_13.title': '영화 캐릭터와의 캐릭터 일관성 셀피',
    'prompt.1_13.description': '당신의 특징을 유지하면서 영화 캐릭터와 셀피 찍기',
    'prompt.1_14.title': '미술관 전시 셀피',
    'prompt.1_14.description': '고전적인 유화와 함께한 상업용 사진',
    'prompt.1_15.title': '컴팩트 카메라 화면 표시',
    'prompt.1_15.description': '컴팩트 디지털 카메라 화면에 표시된 사진',
    'prompt.1_16.title': '매거진 커버 초상화',
    'prompt.1_16.description': '광택 있는 매거진 커버 생성',
    'prompt.1_17.title': '럭셔리 제품 사진',
    'prompt.1_17.description': '떠다니는 럭셔리 제품 사진 생성',
    'prompt.2_1.title': '스타워즈 "왈도를 찾아라"',
    'prompt.2_1.description': '밀집된 군중과 특정 캐릭터 인식을 처리하는 모델의 능력을 테스트하는 복잡한 프롬프트.',
    'prompt.2_2.title': '세월에 따른 노화',
    'prompt.2_2.description': '단일 주제에 대한 시간적 일관성과 노화 효과를 보여줍니다.',
    'prompt.2_3.title': '재귀적 시각화',
    'prompt.2_3.description': '무한 루프 논리(Droste 효과)를 처리하는 모델의 능력을 보여줍니다.',
    'prompt.2_4.title': '좌표 시각화',
    'prompt.2_4.description': '순수하게 위도/경도 좌표를 기반으로 특정 위치와 시간을 생성합니다.',
    'prompt.2_5.title': '개념적 시각화',
    'prompt.2_5.description': '특정 그룹(엔지니어)이 랜드마크를 시각화하는 방법의 해석적 렌더링.',
    'prompt.2_6.title': '문자 그대로 해석',
    'prompt.2_6.description': '파일명을 시각적 주제로 해석합니다.',
    'prompt.2_7.title': '다중 주제 합성',
    'prompt.2_7.description': '여러 입력 초상화를 특정 표정을 가진 단일 응집력 있는 그룹 사진으로 결합합니다.',
    'prompt.2_8.title': '화이트보드 마커 아트',
    'prompt.2_8.description': '유리 질감에 특정 그리기 매체(바랜 마커) 시뮬레이션.',
    'prompt.2_9.title': '분할 뷰 3D 렌더 - iPhone 17 Pro',
    'prompt.2_9.description': '현실적인 왼쪽 절반과 와이어프레임 오른쪽 절반을 가진 3D 렌더 생성',
    'prompt.2_10.title': '랜드마크가 있는 미국 3D 디오라마',
    'prompt.2_10.description': '미국 랜드마크의 아이소메트릭 3D 디오라마 생성',
    'prompt.2_11.title': '유명 음식으로 만든 미국 지도',
    'prompt.2_11.description': '유명 음식으로 만든 미국 주 지도 생성',
    'prompt.2_12.title': '도시 최고층 건물 3D 만화 뷰',
    'prompt.2_12.description': '도시 최고층 건물의 미니어처 3D 뷰 생성',
    'prompt.2_13.title': '3D 아이소메트릭 홈 오피스 일러스트',
    'prompt.2_13.description': '홈 오피스의 3D 아이소메트릭 뷰 생성',
    'prompt.2_14.title': '이모지 조합 - 선글라스를 쓴 바나나',
    'prompt.2_14.description': 'Google 스타일 디자인으로 이모지 결합',
    'prompt.2_15.title': '찢어진 종이 아트 효과',
    'prompt.2_15.description': '이미지의 특정 영역에 찢어진 종이 효과 추가',
    'prompt.2_16.title': '시네마틱 키프레임 생성기',
    'prompt.2_16.description': '참조 이미지에서 시네마틱 키프레임과 스토리보드 생성',
    'prompt.2_17.title': '좌표가 있는 포토북 스타일 매거진 커버',
    'prompt.2_17.description': '정확한 좌표와 함께 9:16 종횡비를 완전히 활용하는 아름다운 포토북 스타일 매거진 커버.',
    'prompt.2_18.title': '떠다니는 국가 섬 디오라마',
    'prompt.2_18.description': '특정 국가 모양의 떠다니는 미니어처 섬의 하이퍼 리얼리스틱 디지털 포스터.',
    'prompt.2_19.title': '소설 장면 3D 포스터',
    'prompt.2_19.description': '미니어처 디오라마 효과를 가진 소설이나 영화를 위한 3D 포스터 디자인.',
    'prompt.2_20.title': '미니어처 수영장 디오라마',
    'prompt.2_20.description': '수영장으로 사용되는 초대형 컨테이너를 특징으로 하는 초현실적인 미니어처 월드 콜라주 포스터.',
    'prompt.2_21.title': '크리스마스 장식 3D 캐릭터',
    'prompt.2_21.description': '크리스마스 장식 안에 귀여운 3D 캐릭터로 자신을 변환합니다.',
    'prompt.2_22.title': '주름 다림질',
    'prompt.2_22.description': '주름을 다림질하는 미니어처 다리미로 안티에이징에 대한 초현실적인 해석.',
    'prompt.2_23.title': '완벽한 아이소메트릭 사진',
    'prompt.2_23.description': '완벽하게 아이소메트릭인 우연한 사진 생성.',
    'prompt.2_24.title': '극단적 광각 폰 화면 교체',
    'prompt.2_24.description': '극단적인 광각과 폰 화면 교체로 사진 편집.',
    'prompt.2_25.title': '쇼핑 윈도우 만화 반사',
    'prompt.2_25.description': '만화 버전을 보여주는 쇼핑 윈도우 옆에 있는 사람의 사진 생성.',
    'prompt.2_26.title': '도시 3D LED 디스플레이',
    'prompt.2_26.description': '도시 환경에서 큰 L자형 3D LED 화면이 있는 장면 생성.',
    'prompt.2_27.title': '차원 간 액체 부음',
    'prompt.2_27.description': '물리적 세계의 액체가 디지털 화면으로 쏟아지는 초현실적인 장면.',
    'prompt.2_28.title': '어안 말차 소녀',
    'prompt.2_28.description': '말차 음료를 마시는 소녀의 초광각 어안 사진.',
    'prompt.2_29.title': 'Canon IXUS 미학 초상화',
    'prompt.2_29.description': 'Canon IXUS 포인트 앤 슛 카메라 미학으로 초상화 생성.',
    'prompt.2_30.title': '하이퍼리얼리스틱 애니메 초상화 스포트라이트',
    'prompt.2_30.description': '극적인 스포트라이트 조명을 가진 하이퍼리얼리스틱 애니메 스타일 초상화.',
    'prompt.3_1.title': '개념 시각화 (텍스트를 인포그래픽으로)',
    'prompt.3_1.description': '텍스트 개념을 명확하고 교육적인 벡터 일러스트로 변환합니다.',
    'prompt.3_2.title': '어린이 크레용 여행 일기 일러스트레이터',
    'prompt.3_2.description': '도시를 위한 어린이 같은 여행 일기 일러스트 생성',
    'prompt.3_3.title': '재무 Sankey 다이어그램 시각화',
    'prompt.3_3.description': '전문적인 재무 Sankey 다이어그램 생성',
    'prompt.3_4.title': '시각적 레시피: 물김치',
    'prompt.3_4.description': '손글씨 느낌의 한글 라벨이 포함된 수채화 스타일 물김치 레시피.',
    'prompt.3_5.title': '3D 미니어처 디오라마: 나우시카',
    'prompt.3_5.description': 'Unreal Engine 5 스타일의 정교한 바람계곡의 나우시카 3D 디오라마.',
    'prompt.4_1.title': '가상 모델 착용',
    'prompt.4_1.description': '직물 질감과 조명 통합을 유지하면서 모델에 특정 의상을 입힙니다.',
    'prompt.4_2.title': '전문 제품 사진',
    'prompt.4_2.description': '지저분한 배경에서 제품을 분리하여 고급 상업용 스튜디오 설정에 배치합니다.',
    'prompt.4_3.title': '3D 치비 스타일 미니어처 브랜드 스토어',
    'prompt.4_3.description': '브랜드를 위한 미니어처 3D 스토어 생성',
    'prompt.4_4.title': '방 가구 배치 시각화',
    'prompt.4_4.description': '빈 방에서 가구가 어떻게 보일지 시각화',
    'prompt.5_1.title': '손그림 플로우차트를 기업용 차트로',
    'prompt.5_1.description': '화이트보드 스케치를 명확한 "McKinsey 스타일" 벡터 프레젠테이션으로 변환합니다.',
    'prompt.5_2.title': 'UI 손그림 스케치를 고품질 프로토타입으로',
    'prompt.5_2.description': '와이어프레임 낙서를 현실적인 모바일 앱 목업으로 변환합니다.',
    'prompt.5_3.title': '매거진 레이아웃 생성기',
    'prompt.5_3.description': '복잡한 타이포그래피를 가진 인쇄 형식의 기사를 시각화하는 데 완벽합니다.',
    'prompt.6_1.title': '구도 구출 (스마트 아웃페인팅)',
    'prompt.6_1.description': '일치하는 풍경을 지능적으로 생성하여 이미지 비율(예: 16:9)을 확장합니다.',
    'prompt.6_2.title': '스마트 군중 제거',
    'prompt.6_2.description': '배경에서 원하지 않는 사람을 제거하고 공간을 논리적인 질감으로 채웁니다.',
    'prompt.6_3.title': '얼굴 인식 CCTV 시뮬레이션',
    'prompt.6_3.description': '얼굴 인식이 있는 고각 CCTV 감시 샷 생성',
    'prompt.7_1.title': '하드 퍼니싱 미리보기 (평면도를 디자인으로)',
    'prompt.7_1.description': '간단한 2D 지도에서 원근 뷰와 3D 평면도를 포함한 완전한 디자인 프레젠테이션 보드 생성.',
    'prompt.8_1.title': '바이럴 커버 이미지 (유튜브/도우인/틱톡)',
    'prompt.8_1.description': '텍스트 오버레이, 과장된 표현, 밝은 그래픽으로 매력적인 썸네일을 생성합니다.',
    'prompt.8_2.title': '상업용 홍보 포스터',
    'prompt.8_2.description': '통합 텍스트와 고품질 제품 사진으로 전문 판매 포스터를 디자인합니다.',
    'prompt.9_1.title': '실제 매장/여행 번역',
    'prompt.9_1.description': '원본 표면 질감(벽, 종이, 기름)을 유지하면서 메뉴나 간판을 번역합니다.',
    'prompt.9_2.title': '디지털 콘텐츠 현지화 (만화/밈)',
    'prompt.9_2.description': '텍스트 버블을 지우고 일치하는 폰트로 콘텐츠를 교체하여 만화나 밈을 번역합니다.',
    'prompt.10_1.title': '3D 블라인드 박스 스타일 아바타',
    'prompt.10_1.description': '초상화를 귀여운 C4D 스타일 "Pop Mart" 장난감 캐릭터로 변환합니다.',
    'prompt.10_2.title': '펫 밈 생성',
    'prompt.10_2.description': '펫 사진을 미니멀한 손그림 재미있는 스티커로 변환합니다.',
    'prompt.10_3.title': '다양한 포즈의 Y2K 스크랩북 포스터',
    'prompt.10_3.description': '다양한 포즈를 가진 Y2K 스타일 스크랩북 포스터 생성',
    'prompt.10_4.title': '일본 고등학생 스냅 사진',
    'prompt.10_4.description': '일본 고등학생 스타일의 스냅샷 생성',
    'prompt.10_5.title': 'AI 피부 분석 및 스킨케어 루틴',
    'prompt.10_5.description': '피부를 분석하고 루틴 추천 제공',
  },
  en: {
    'app.title': 'Awesome Nano Banana Pro',
    'hero.subtitle': 'Curated Collection',
    'hero.title': 'Awesome Nano Banana Pro',
    'hero.description': 'A curated collection of the best Nano Banana prompts, image generation styles for advanced AI visual experiments.',
    'hero.tryButton': 'Try Nano Banana Pro',
    'gallery.title': 'Explore Prompts',
    'gallery.description': 'Discover {count} carefully curated prompts for Nano Banana Pro',
    'gallery.noResults': 'No prompts found in this category.',
    'nav.print': 'Print',
    'card.view': 'View',
    'card.copy': 'Copy',
    'card.copied': 'Copied!',
    'card.source': 'Source',
    'modal.prompt': 'Prompt',
    'modal.copyPrompt': 'Copy Prompt',
    'footer.madeWith': 'Made with ❤️ for the AI community',
    'footer.lastUpdated': 'Last updated',
    'footer.viewOnGitHub': 'View on GitHub',
    'category.all': 'All',
    'category.1': 'Photorealism & Aesthetics',
    'category.2': 'Creative Experiments',
    'category.3': 'Education & Knowledge',
    'category.4': 'E-commerce & Virtual Studio',
    'category.5': 'Workplace & Productivity',
    'category.6': 'Photo Editing & Restoration',
    'category.7': 'Interior Design',
    'category.8': 'Social Media & Marketing',
    'category.9': 'Daily Life & Translation',
    'category.10': 'Social Networking & Avatars',
    // 프롬프트 번역
    'prompt.1_1.title': 'Hyper-Realistic Crowd Composition',
    'prompt.1_1.description': 'Handling complex compositions with multiple famous faces and specific lighting.',
    'prompt.1_2.title': '2000s Mirror Selfie',
    'prompt.1_2.description': 'A structured JSON prompt to generate an authentic early-2000s aesthetic with flash photography and nostalgic elements.',
    'prompt.1_3.title': "Victoria's Secret Style Photoshoot",
    'prompt.1_3.description': 'Great for creating high-glamour, backstage-style fashion photography with intricate details.',
    'prompt.1_4.title': '1990s Camera Style Portrait',
    'prompt.1_4.description': "Test the model's ability to replicate specific film textures, flash photography, and era-specific atmosphere.",
    'prompt.1_5.title': 'One-Click Business Photo (Silicon Valley Style)',
    'prompt.1_5.description': 'Transforms casual photos into professional studio headshots using specific lens and lighting instructions.',
    'prompt.1_6.title': 'Emotional Film Photography',
    'prompt.1_6.description': 'Creates a cinematic, nostalgic "Kodak Portra" look while maintaining facial consistency.',
    'prompt.1_7.title': 'Professional Headshot Creator',
    'prompt.1_7.description': 'Create a professional profile photo from a selfie',
    'prompt.1_8.title': 'Hyperrealistic Anime Portrait in Spotlight',
    'prompt.1_8.description': 'A hyperrealistic anime-style portrait with dramatic lighting',
    'prompt.1_9.title': 'Bathroom Mirror Selfie',
    'prompt.1_9.description': 'Create a candid mirror selfie with specific styling and composition',
    'prompt.1_10.title': 'Chalkboard Anime Art Documentation',
    'prompt.1_10.description': 'Photorealistic documentation of a chalkboard anime drawing',
    'prompt.1_11.title': 'Portrait with Puppy in Snow',
    'prompt.1_11.description': 'Create a winter portrait with a puppy',
    'prompt.1_12.title': 'Fisheye Movie Character Selfie',
    'prompt.1_12.description': 'A 360-degree selfie with movie characters',
    'prompt.1_13.title': 'Character Consistency Selfie with Movie Character',
    'prompt.1_13.description': 'Take a selfie with a movie character while preserving your features',
    'prompt.1_14.title': 'Museum Art Exhibition Selfie',
    'prompt.1_14.description': 'A commercial-grade photo with a classical oil painting',
    'prompt.1_15.title': 'Compact Camera Screen Display',
    'prompt.1_15.description': 'A photo displayed on a compact digital camera screen',
    'prompt.1_16.title': 'Magazine Cover Portrait',
    'prompt.1_16.description': 'Create a glossy magazine cover',
    'prompt.1_17.title': 'Luxury Product Photography',
    'prompt.1_17.description': 'Create a floating luxury product shot',
    'prompt.2_1.title': 'Star Wars "Where\'s Waldo"',
    'prompt.2_1.description': "A complex prompt testing the model's ability to handle dense crowds and specific character recognition.",
    'prompt.2_2.title': 'Aging Through the Years',
    'prompt.2_2.description': 'Demonstrates temporal consistency and aging effects on a single subject.',
    'prompt.2_3.title': 'Recursive Visuals',
    'prompt.2_3.description': "Demonstrates the model's ability to handle infinite loop logic (Droste effect).",
    'prompt.2_4.title': 'Coordinate Visualization',
    'prompt.2_4.description': 'Generates a specific location and time based purely on latitude/longitude coordinates.',
    'prompt.2_5.title': 'Conceptual Visualization',
    'prompt.2_5.description': 'Interpretative rendering of how a specific group (engineers) visualizes a landmark.',
    'prompt.2_6.title': 'Literal Interpretation',
    'prompt.2_6.description': 'Interprets a filename as a visual subject.',
    'prompt.2_7.title': 'Multi-Subject Compositing',
    'prompt.2_7.description': 'Combines multiple input portraits into a single cohesive group photo with a specific expression.',
    'prompt.2_8.title': 'Whiteboard Marker Art',
    'prompt.2_8.description': 'Simulating specific drawing media (faded marker) on glass textures.',
    'prompt.2_9.title': 'Split View 3D Render - iPhone 17 Pro',
    'prompt.2_9.description': 'Create a 3D render with realistic left half and wireframe right half',
    'prompt.2_10.title': 'USA 3D Diorama with Landmarks',
    'prompt.2_10.description': 'Create an isometric 3D diorama of US landmarks',
    'prompt.2_11.title': 'US Map Made of Famous Foods',
    'prompt.2_11.description': 'Create a map of US states made of famous foods',
    'prompt.2_12.title': "City's Tallest Buildings 3D Cartoon View",
    'prompt.2_12.description': "Create a miniature 3D view of city's tallest buildings",
    'prompt.2_13.title': '3D Isometric Home Office Illustration',
    'prompt.2_13.description': 'Create a 3D isometric view of a home office',
    'prompt.2_14.title': 'Emoji Combination - Banana with Sunglasses',
    'prompt.2_14.description': 'Combine emojis in a Google-style design',
    'prompt.2_15.title': 'Torn Paper Art Effect',
    'prompt.2_15.description': 'Add torn paper effect to specific areas of an image',
    'prompt.2_16.title': 'Cinematic Keyframe Generator',
    'prompt.2_16.description': 'Generates cinematic keyframes and storyboards from a reference image',
    'prompt.2_17.title': 'Photo Book Style Magazine Cover with Coordinates',
    'prompt.2_17.description': 'A beautiful, photo book style magazine cover that fully utilizes the 9:16 aspect ratio with precise coordinates.',
    'prompt.2_18.title': 'Floating Country Island Diorama',
    'prompt.2_18.description': 'A hyper-realistic digital poster of a floating miniature island shaped like a specific country.',
    'prompt.2_19.title': 'Novel Scene 3D Poster',
    'prompt.2_19.description': 'A 3D poster design for novels or films with a miniature diorama effect.',
    'prompt.2_20.title': 'Miniature Swimming Pool Diorama',
    'prompt.2_20.description': 'Surreal miniature-world collage poster featuring an oversized container as a swimming pool.',
    'prompt.2_21.title': 'Christmas Ornament 3D Character',
    'prompt.2_21.description': 'Transform yourself into a cute 3D character inside a Christmas ornament.',
    'prompt.2_22.title': 'Ironing Out Wrinkles',
    'prompt.2_22.description': 'A surreal take on anti-aging with a miniature iron smoothing out wrinkles.',
    'prompt.2_23.title': 'Perfectly Isometric Photography',
    'prompt.2_23.description': 'Create a captured photo that just happens to be perfectly isometric.',
    'prompt.2_24.title': 'Extreme Wide Angle Phone Screen Replacement',
    'prompt.2_24.description': 'Edit photo with extreme wide angle and phone screen replacement.',
    'prompt.2_25.title': 'Shop Window Cartoon Reflection',
    'prompt.2_25.description': 'Create a photograph of a person next to a shop window showing their cartoon version.',
    'prompt.2_26.title': 'Urban 3D LED Display',
    'prompt.2_26.description': 'Create a scene with a large L-shaped 3D LED screen in an urban environment.',
    'prompt.2_27.title': 'Trans-Dimensional Liquid Pour',
    'prompt.2_27.description': 'A surreal scene where liquid from the physical world pours into a digital screen.',
    'prompt.2_28.title': 'Fisheye Matcha Girl',
    'prompt.2_28.description': 'Ultra wide fisheye photo of a girl sipping a matcha drink.',
    'prompt.2_29.title': 'Canon IXUS Aesthetic Portrait',
    'prompt.2_29.description': 'Create a portrait with Canon IXUS point-and-shoot camera aesthetic.',
    'prompt.2_30.title': 'Hyperrealistic Anime Portrait Spotlight',
    'prompt.2_30.description': 'Hyperrealistic anime-style portrait with dramatic spotlight lighting.',
    'prompt.3_1.title': 'Concept Visualization (Text to Infographic)',
    'prompt.3_1.description': 'Converts textual concepts into clear, educational vector illustrations.',
    'prompt.3_2.title': "Kids' Crayon Travel Journal Illustrator",
    'prompt.3_2.description': 'Generate a childlike travel journal illustration for a city',
    'prompt.3_3.title': 'Financial Sankey Diagram Visualization',
    'prompt.3_3.description': 'Create a professional financial Sankey diagram',
    'prompt.3_4.title': 'Visual Recipe: Water Kimchi',
    'prompt.3_4.description': 'An artistic watercolor visual recipe for Korean Water Kimchi with handwritten-style Korean labels.',
    'prompt.3_5.title': '3D Miniature Diorama: Nausicaä',
    'prompt.3_5.description': 'Detailed 3D isometric miniature diorama of Nausicaä of the Valley of the Wind using Unreal Engine 5 style.',
    'prompt.4_1.title': 'Virtual Model Try-On',
    'prompt.4_1.description': 'Dresses a model in a specific garment while preserving fabric texture and lighting integration.',
    'prompt.4_2.title': 'Professional Product Photography',
    'prompt.4_2.description': 'Isolates products from messy backgrounds and places them in a high-end commercial studio setting.',
    'prompt.4_3.title': '3D Chibi-Style Miniature Brand Store',
    'prompt.4_3.description': 'Create a miniature 3D store for a brand',
    'prompt.4_4.title': 'Room Furnishing Visualization',
    'prompt.4_4.description': 'Visualize how furniture would look in an empty room',
    'prompt.5_1.title': 'Hand-drawn Flowchart to Corporate Charts',
    'prompt.5_1.description': 'Converts whiteboard sketches into clear, "McKinsey-style" vector presentations.',
    'prompt.5_2.title': 'UI Hand-drawn Sketch to High-Fidelity Prototype',
    'prompt.5_2.description': 'Transforms wireframe scribbles into realistic mobile app mockups.',
    'prompt.5_3.title': 'Magazine Layout Generator',
    'prompt.5_3.description': 'Perfect for visualizing articles in print format with complex typography.',
    'prompt.6_1.title': 'Composition Rescue (Smart Outpainting)',
    'prompt.6_1.description': 'Expands image ratios (e.g., to 16:9) by intelligently generating matching scenery.',
    'prompt.6_2.title': 'Smart Crowd Removal',
    'prompt.6_2.description': 'Removes unwanted people from backgrounds and fills the space with logical textures.',
    'prompt.6_3.title': 'Face Detection CCTV Simulation',
    'prompt.6_3.description': 'Create a high angle CCTV surveillance shot with face detection',
    'prompt.7_1.title': 'Hard Furnishing Preview (Floor Plan to Design)',
    'prompt.7_1.description': 'Generates a complete design presentation board including perspective views and 3D floor plans from a simple 2D map.',
    'prompt.8_1.title': 'Viral Cover Image (Youtube/Douyin/TikTok)',
    'prompt.8_1.description': 'Creates engaging thumbnails with text overlays, exaggerated expressions, and bright graphics.',
    'prompt.8_2.title': 'Commercial Promotional Poster',
    'prompt.8_2.description': 'Designs professional sales posters with integrated text and high-quality product photography.',
    'prompt.9_1.title': 'Physical Store/Travel Translation',
    'prompt.9_1.description': 'Translates menus or signs while preserving the original surface texture (wall, paper, grease).',
    'prompt.9_2.title': 'Digital Content Localization (Comics/Memes)',
    'prompt.9_2.description': 'Translates comics or memes by scrubbing text bubbles and replacing content with matching fonts.',
    'prompt.10_1.title': '3D Blind Box Style Avatar',
    'prompt.10_1.description': 'Converts portraits into cute, C4D-style "Pop Mart" toy characters.',
    'prompt.10_2.title': 'Pet Meme Creation',
    'prompt.10_2.description': 'Turns pet photos into minimalist, hand-drawn funny stickers.',
    'prompt.10_3.title': 'Y2K Scrapbook Poster with Multiple Poses',
    'prompt.10_3.description': 'Create a Y2K-style scrapbook poster with multiple poses',
    'prompt.10_4.title': 'Japanese High School Student Snap Photo',
    'prompt.10_4.description': 'Create a snapshot in the style of a Japanese high school student',
    'prompt.10_5.title': 'AI Skin Analysis and Skincare Routine',
    'prompt.10_5.description': 'Analyze skin and provide routine recommendations',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || (navigator.language.startsWith('ko') ? 'ko' : 'en');
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'ko' ? 'en' : 'ko'));
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    // 프롬프트 번역 키인 경우 fallback 처리
    const translationKey = key as keyof typeof translations['ko'];
    let text = translations[language][translationKey];

    // 번역이 없으면 영어를 fallback으로 사용
    if (!text && language === 'ko') {
      text = translations['en'][translationKey];
    }

    // 여전히 없으면 키 자체를 반환
    if (!text) {
      text = key;
    }

    // 파라미터 치환
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(`{${paramKey}}`, String(value));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

